workspace:
  launch:
    button:
      name: ğŸ›« èµ·é£
      description: ğŸ’ª é€æ­¥è¿ˆå‘è¿ç»´çš„å››ä¸ªç°ä»£åŒ–ï¼šè§„èŒƒåŒ–ï¼Œæ ‡å‡†åŒ–ï¼Œé«˜æ•ˆåŒ–ï¼Œä¼˜é›…åŒ–
      hoverImage: https://cnb.cool/66666/resource/-/git/raw/main/img/qifei.gif
    cpus: 8
    disabled: false
    autoOpenWebIDE: false

issue:
  button:
    description: ğŸ™‹ğŸ»â€â™€ï¸ I Have A Question
    hoverImage: "https://cnb.cool/66666/resource/-/git/raw/main/img/jushou.jpg"

fork:
  button:
    description: ğŸ«µ å¹´è½»äººï¼Œä½ å¾ˆçœ¼å…‰
    hoverImage: "https://cnb.cool/66666/resource/-/git/raw/main/img/trump.gif"
